POST http://127.0.0.1:4293/paidiki-xara
Content-Type: application/json

{
    "code": "val a = 4\nconsole.log(a)",
    "grid": [[
    { "type": "OPEN" },
    { "type": "CLOSEDSWITCH" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" }
    ], [
    {"type":  "CLOSEDSWITCH" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "BLOCKED" }
    ], [
    {"type":  "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" }
    ]],
    "players": [{
    "name": "player1",
    "p": { "x": 0, "y": 0, "dir": "RIGHT" }
    }],
    "energy": 9999
}

###

POST http://127.0.0.1:4293/paidiki-xara
Content-Type: application/json

{
    "code": "for (i in 1 .. 4) {\n  console.log(i)\n}",
    "grid": [[
    { "type": "OPEN" },
    { "type": "CLOSEDSWITCH" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" }
    ], [
    {"type":  "CLOSEDSWITCH" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "BLOCKED" }
    ], [
    {"type":  "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" }
    ]],
    "players": [{
    "name": "player1",
    "p": { "x": 0, "y": 0, "dir": "RIGHT" }
    }],
    "energy": 9999
}


###

POST http://127.0.0.1:4293/paidiki-xara
Content-Type: application/json

{
  "code": "moveForward()",
  "grid": [[
    { "type": "OPEN" },
    { "type": "CLOSEDSWITCH" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" }
  ], [
    {"type":  "CLOSEDSWITCH" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "BLOCKED" }
  ], [
    {"type":  "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" }
  ]],
  "players": [{
    "name": "player1",
    "p": { "x": 0, "y": 0, "dir": "RIGHT" }
  }],
  "energy": 9999
}

###

POST http://127.0.0.1:4293/paidiki-xara
Content-Type: application/json

{
  "code": "val totalGem = 2\nvar collected = 0\n\nfun turnRight() {\n    turnLeft()\n    turnLeft()\n    turnLeft()\n}\n\nwhile (collected < totalGem) {\n    if (isOnGem) {\n        collectGem()\n        collected += 1\n    }\n    if (isOnClosedSwitch) {\n        toggleSwitch()\n    }\n    if (!isBlockedRight) {\n        turnRight()\n        moveForward()\n    } else {\n        if (isBlocked) {\n            while (isBlocked) {\n                turnLeft()\n            }\n        }\n        moveForward()\n    }\n}",
  "grid": [[
    { "type": "OPEN" },
    { "type": "CLOSEDSWITCH" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" },
    { "type": "BLOCKED" }
  ], [
    {"type":  "CLOSEDSWITCH" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "OPEN" },
    { "type": "BLOCKED" }
  ], [
    {"type":  "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" },
    { "type": "GEM" },
    { "type": "BLOCKED" }
  ]],
  "players": [{
    "name": "player1",
    "p": { "x": 0, "y": 0, "dir": "RIGHT" }
  }],
  "energy": 9999
}

###

POST http://127.0.0.1:4293/paidiki-xara
Content-Type: application/json

{
  "value": "func foo(a: Int, b: String) -> Int {\n    print(b)\n   a += 1\n   return a}\n\nlet b = 3\nlet c = foo(b, \"bar\")\nprint(c)"
}

###